name: Send API Request On Commit

on:
  push:
    branches:
      - main  
jobs:
  send-api-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Send API Request
        run: |
          curl -X POST   -H 'Content-Type: application/json'   -d '{"jsonrpc": "2.0", "method": "call","params": {"service": "object", "method": "execute", "args": ["demo16", 2, "7F1gp[2M0%7M", "product.template", "create", {"name" : "demo","default_code" : "AZUL01010"}]}}'   http://demo16.viraweb123.ir/jsonrpc --max-time 10